#!/usr/bin/env bash
# 2020-6-13 publish test

# office-home
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set home --source_path data/list/home/Art_65.txt --target_path data/list/home/Clipart_65.txt --test_path data/list/home/Clipart_65.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set home --source_path data/list/home/Art_65.txt --target_path data/list/home/Product_65.txt --test_path data/list/home/Product_65.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set home --source_path data/list/home/Art_65.txt --target_path data/list/home/RealWorld_65.txt --test_path data/list/home/RealWorld_65.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set home --source_path data/list/home/Clipart_65.txt --target_path data/list/home/Art_65.txt --test_path data/list/home/Art_65.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set home --source_path data/list/home/Clipart_65.txt --target_path data/list/home/Product_65.txt --test_path data/list/home/Product_65.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set home --source_path data/list/home/Clipart_65.txt --target_path data/list/home/RealWorld_65.txt --test_path data/list/home/RealWorld_65.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set home --source_path data/list/home/Product_65.txt --target_path data/list/home/Art_65.txt --test_path data/list/home/Art_65.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set home --source_path data/list/home/Product_65.txt --target_path data/list/home/Clipart_65.txt --test_path data/list/home/Clipart_65.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set home --source_path data/list/home/Product_65.txt --target_path data/list/home/RealWorld_65.txt --test_path data/list/home/RealWorld_65.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set home --source_path data/list/home/RealWorld_65.txt --target_path data/list/home/Art_65.txt --test_path data/list/home/Art_65.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set home --source_path data/list/home/RealWorld_65.txt --target_path data/list/home/Clipart_65.txt --test_path data/list/home/Clipart_65.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set home --source_path data/list/home/RealWorld_65.txt --target_path data/list/home/Product_65.txt --test_path data/list/home/Product_65.txt --gpu 7


# office-31
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set office --source_path data/list/office/amazon_31.txt --target_path data/list/office/webcam_31.txt --test_path data/list/office/webcam_31.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set office --source_path data/list/office/amazon_31.txt --target_path data/list/office/dslr_31.txt --test_path data/list/office/dslr_31.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set office --source_path data/list/office/webcam_31.txt --target_path data/list/office/amazon_31.txt --test_path data/list/office/amazon_31.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set office --source_path data/list/office/webcam_31.txt --target_path data/list/office/dslr_31.txt --test_path data/list/office/dslr_31.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set office --source_path data/list/office/dslr_31.txt --target_path data/list/office/amazon_31.txt --test_path data/list/office/amazon_31.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set office --source_path data/list/office/dslr_31.txt --target_path data/list/office/webcam_31.txt --test_path data/list/office/webcam_31.txt --gpu 7

# ImageCLEF
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set office --source_path data/list/clef/i_12.txt --target_path data/list/clef/p_12.txt --test_path data/list/clef/p_12.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set office --source_path data/list/clef/p_12.txt --target_path data/list/clef/i_12.txt --test_path data/list/clef/i_12.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set office --source_path data/list/clef/i_12.txt --target_path data/list/clef/c_12.txt --test_path data/list/clef/c_12.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set office --source_path data/list/clef/c_12.txt --target_path data/list/clef/i_12.txt --test_path data/list/clef/i_12.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set office --source_path data/list/clef/c_12.txt --target_path data/list/clef/p_12.txt --test_path data/list/clef/p_12.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --data_set office --source_path data/list/clef/p_12.txt --target_path data/list/clef/c_12.txt --test_path data/list/clef/c_12.txt --gpu 7


# DomainNet 50
# source domain clipart_train
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domian infograph_train
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domain painting_train
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domain quickdraw_train
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domain real_train
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domain sketch_train
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 50 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_50/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7


# DomainNet 101
# source domain clipart_train
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domian infograph_train
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domain painting_train
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domain quickdraw_train
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domain real_train
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domain sketch_train
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 101 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_101/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7


# DomainNet 152
# source domain clipart_train
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/clipart_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domian infograph_train
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/infograph_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domain painting_train
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/painting_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domain quickdraw_train
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/quickdraw_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domain real_train
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/real_train.txt --target_path data/list/domainnet/sketch_train.txt --test_path data/list/domainnet/sketch_test.txt --gpu 7
# source domain sketch_train
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/clipart_train.txt --test_path data/list/domainnet/clipart_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/infograph_train.txt --test_path data/list/domainnet/infograph_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/painting_train.txt --test_path data/list/domainnet/painting_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/quickdraw_train.txt --test_path data/list/domainnet/quickdraw_test.txt --gpu 7
python3 train_dcan.py --net 152 --lr 1e-4 --random_prob 0.8 --beta_off 0.1 --alpha_off 1.5 --batch_size 36 --output_path publish_test_152/ --max_iter 20001 --val_iter 500 --dset domainnet --source_path data/list/domainnet/sketch_train.txt --target_path data/list/domainnet/real_train.txt --test_path data/list/domainnet/real_test.txt --gpu 7
